# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\arnas\Documents\GitHub\studentai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\arnas\Documents\GitHub\studentai

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\arnas\Documents\GitHub\studentai\CMakeFiles C:\Users\arnas\Documents\GitHub\studentai\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\arnas\Documents\GitHub\studentai\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named student

# Build rule for target.
student: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 student
.PHONY : student

# fast build rule for target.
student/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/build
.PHONY : student/fast

src/additional_functions.obj: src/additional_functions.cpp.obj
.PHONY : src/additional_functions.obj

# target to build an object file
src/additional_functions.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/additional_functions.cpp.obj
.PHONY : src/additional_functions.cpp.obj

src/additional_functions.i: src/additional_functions.cpp.i
.PHONY : src/additional_functions.i

# target to preprocess a source file
src/additional_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/additional_functions.cpp.i
.PHONY : src/additional_functions.cpp.i

src/additional_functions.s: src/additional_functions.cpp.s
.PHONY : src/additional_functions.s

# target to generate assembly for a file
src/additional_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/additional_functions.cpp.s
.PHONY : src/additional_functions.cpp.s

src/file_functions.obj: src/file_functions.cpp.obj
.PHONY : src/file_functions.obj

# target to build an object file
src/file_functions.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/file_functions.cpp.obj
.PHONY : src/file_functions.cpp.obj

src/file_functions.i: src/file_functions.cpp.i
.PHONY : src/file_functions.i

# target to preprocess a source file
src/file_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/file_functions.cpp.i
.PHONY : src/file_functions.cpp.i

src/file_functions.s: src/file_functions.cpp.s
.PHONY : src/file_functions.s

# target to generate assembly for a file
src/file_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/file_functions.cpp.s
.PHONY : src/file_functions.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/program_choice.obj: src/program_choice.cpp.obj
.PHONY : src/program_choice.obj

# target to build an object file
src/program_choice.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/program_choice.cpp.obj
.PHONY : src/program_choice.cpp.obj

src/program_choice.i: src/program_choice.cpp.i
.PHONY : src/program_choice.i

# target to preprocess a source file
src/program_choice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/program_choice.cpp.i
.PHONY : src/program_choice.cpp.i

src/program_choice.s: src/program_choice.cpp.s
.PHONY : src/program_choice.s

# target to generate assembly for a file
src/program_choice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/program_choice.cpp.s
.PHONY : src/program_choice.cpp.s

src/random_generating.obj: src/random_generating.cpp.obj
.PHONY : src/random_generating.obj

# target to build an object file
src/random_generating.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/random_generating.cpp.obj
.PHONY : src/random_generating.cpp.obj

src/random_generating.i: src/random_generating.cpp.i
.PHONY : src/random_generating.i

# target to preprocess a source file
src/random_generating.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/random_generating.cpp.i
.PHONY : src/random_generating.cpp.i

src/random_generating.s: src/random_generating.cpp.s
.PHONY : src/random_generating.s

# target to generate assembly for a file
src/random_generating.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/random_generating.cpp.s
.PHONY : src/random_generating.cpp.s

src/student.obj: src/student.cpp.obj
.PHONY : src/student.obj

# target to build an object file
src/student.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/student.cpp.obj
.PHONY : src/student.cpp.obj

src/student.i: src/student.cpp.i
.PHONY : src/student.i

# target to preprocess a source file
src/student.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/student.cpp.i
.PHONY : src/student.cpp.i

src/student.s: src/student.cpp.s
.PHONY : src/student.s

# target to generate assembly for a file
src/student.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/student.cpp.s
.PHONY : src/student.cpp.s

src/student_functions.obj: src/student_functions.cpp.obj
.PHONY : src/student_functions.obj

# target to build an object file
src/student_functions.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/student_functions.cpp.obj
.PHONY : src/student_functions.cpp.obj

src/student_functions.i: src/student_functions.cpp.i
.PHONY : src/student_functions.i

# target to preprocess a source file
src/student_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/student_functions.cpp.i
.PHONY : src/student_functions.cpp.i

src/student_functions.s: src/student_functions.cpp.s
.PHONY : src/student_functions.s

# target to generate assembly for a file
src/student_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/student_functions.cpp.s
.PHONY : src/student_functions.cpp.s

src/testavimas.obj: src/testavimas.cpp.obj
.PHONY : src/testavimas.obj

# target to build an object file
src/testavimas.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/testavimas.cpp.obj
.PHONY : src/testavimas.cpp.obj

src/testavimas.i: src/testavimas.cpp.i
.PHONY : src/testavimas.i

# target to preprocess a source file
src/testavimas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/testavimas.cpp.i
.PHONY : src/testavimas.cpp.i

src/testavimas.s: src/testavimas.cpp.s
.PHONY : src/testavimas.s

# target to generate assembly for a file
src/testavimas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\student.dir\build.make CMakeFiles/student.dir/src/testavimas.cpp.s
.PHONY : src/testavimas.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... student
	@echo ... src/additional_functions.obj
	@echo ... src/additional_functions.i
	@echo ... src/additional_functions.s
	@echo ... src/file_functions.obj
	@echo ... src/file_functions.i
	@echo ... src/file_functions.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/program_choice.obj
	@echo ... src/program_choice.i
	@echo ... src/program_choice.s
	@echo ... src/random_generating.obj
	@echo ... src/random_generating.i
	@echo ... src/random_generating.s
	@echo ... src/student.obj
	@echo ... src/student.i
	@echo ... src/student.s
	@echo ... src/student_functions.obj
	@echo ... src/student_functions.i
	@echo ... src/student_functions.s
	@echo ... src/testavimas.obj
	@echo ... src/testavimas.i
	@echo ... src/testavimas.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

